root: /i/proj/scad
name: hcad

c: &c "550d,127x28,0,0[127x2,0,0,3,127x23,0,3{63x23,\
       0,3,4,63x23,64,3,9},127x1,0,27,5]"
      
cv: &cv
  - loop "clear" 2
  - nvim 
  - loop "clear" 2
  - loop "clear" 2
windows:
  - scad: c

models:
  c:
    layout: *c
    panes: *cv
