root: ~/projects/matrix
name: NeoMatrix

windows:
- Programs : programs
- NeoMatrix : neomatrix
- VirtualMachine : matrix

models:

    programs:
        layout: even-vertical
        panes:
        - idea
        - /opt/insomnia/insomnia
       #- docker restart mongodb && mongodb-compass
        - cd ~ && source pgadmin4/bin/activate && pgadmin4

    matrix:
        layout: even-vertical
        dir: powermatrix 
        panes:
        - ranger
        - docker-compose -f ./virtual-machine/docker-compose.yml up -d

    neomatrix:
        layout: even-vertical
        dir: neomatrix 
        panes:
        - ranger
        - docker-compose up -d

