root: /i/root
name: Root

c: &c "b078,116x29,0,0{80x29,0,0[80x1,0,0,19,80x25,\
       0,2,20,80x1,0,28,21],35x29,81,0,22}"
      
cv: &cv
  - loop "clear" 2
  - nvim 
  - loop "clear" 2
  - loop "clear" 2
windows:
  - main: c

models:
  c:
    layout: *c
    panes: *cv
